name: flutter_application_1
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: '>=2.12.0 <4.0.0'  # Null safety compatibility

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4  # Updated to the latest version at the time of writing
  table_calendar: ^3.0.6  # Ensure this is the latest version
  provider: ^6.0.3  # Updated to the latest version
  intl: ^0.19.0  # Ensure compatibility with your Flutter SDK version
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4  # Updated to the latest version
  geolocator: ^8.0.1  # Updated to the latest version
  geocoding: ^2.0.1  # Updated to the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.5.1  # Updated to the latest version

flutter:
  uses-material-design: true
